### ISSUE TITLE
cudaCheckError() failed : invalid device function

### ISSUE THREAD

**Issue by AnranQi** [longcw/yolo2-pytorch#15]
Operating System:ubuntu14.04
cuda8.0 is tested well

When I run `demo.py`, I got the following error message:

load model succ...
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
cudaCheckError() failed : invalid device function

Could anyone provide some advices? Thank you for help.

**Comment by longcw** [comment]
see this https://github.com/longcw/yolo2-pytorch/issues/10
