### ISSUE TITLE
next_batch: still epoch xxx start

### ISSUE THREAD

**Issue by AceCoooool** [longcw/yolo2-pytorch#17]
When I run python demo.py, I always get the epoch xxx start..., and the memroy up!~ I see the `imdb.py` ， it's confuse to me. 
Could everyone give me some advice? 
(I use python3.6)

**Comment by longcw** [comment]
`demo.py` don't use `imdb.py`. What's the error information?
I suggest you write your own dataloader using [torch.utils.data.Dataset](http://pytorch.org/docs/data.html). It is much easier to use than the `imdb.py`.

**Comment by AceCoooool** [comment]
thank you for your reply. I can run the demo, and I want to train by myself, so i run the `train.py`(and it using the ImageDataset in `imdb`--- the superclass of VOCDataset). No error information, but it always run in the part: `except(StopIteration, AttributeError)` in the `next_batch`，so i can not get the batch, and the while never stop(`pool.imap` to the memory, which cause the memory up~).

Thank you for the advise, I will try to write my own dataloder. (and after that, i will close the issue)

**Comment by hyer** [comment]
I run the train.py on GPU mode and I found the memory always increase, which make the train process killed. Can any one help. thx!
