### ISSUE TITLE
error locating .cu files for building reorg layer

### ISSUE THREAD

**Issue by tymokvo** [longcw/yolo2-pytorch#2]
Hi,

This is an exciting project! Unfortunately, I've encountered some errors while getting it running locally...

While trying to build the reorg layer from make.sh (per instructions in the readme), gcc throws the following errors:

`gcc: error: reorg_cuda_kernel.cu: No such file or directory` 
though that file does exist where it is searching for it.

and

`gcc: error: /home/tyler/yolo2-pytorch/layers/roi_pooling/src/cuda/roi_pooling.cu.o: No such file or directory` 
and indeed this one is not present, though I assume this could be caused by the first failure?

gcc and nvcc info if that helps

`gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)`
`Cuda compilation tools, release 8.0, V8.0.44`

Let me know if I there's more info that would be useful.

**Comment by rdcolema** [comment]
I encountered the same error as above with these specs:

`gcc (Ubuntu 4.9.4-2ubuntu1~16.04) 4.9.4`
`Cuda compilation tools, release 8.0, V8.0.44`

**Comment by crazylyf** [comment]
There are minor mistakes in `make.sh`, and `layers/roi_pooling/build.py`. I have created a pull request to fix that problem.
