### ISSUE TITLE
Could not clone the repository

### ISSUE THREAD

**Issue by soumenms2015** [longcw/yolo2-pytorch#38]
Cloning into 'yolo2-pytorch'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Kindly help me !!

**Comment by zuewang** [comment]
Maybe you can use https://github.com/longcw/yolo2-pytorch.git ?

**Comment by linamy85** [comment]
The reason may be that one cannot clone a repo by ssh without registering a public key under your account. Use https method as @zuewang suggested.
