### ISSUE TITLE
The source of yolo-voc.weights.h5

### ISSUE THREAD

**Issue by crazylyf** [longcw/yolo2-pytorch#4]
I'm wondering the source of `yolo-voc.weights.h5`. Is it trained through yolo2-pytorch or darkflow?

**Comment by longcw** [comment]
It is transformed from the weight file released by the author of YOLO (https://pjreddie.com/darknet/yolo/).
This project still cannot train yolo2 well.

**Comment by crazylyf** [comment]
okay, thanks!
