### ISSUE TITLE
size_index is missing for preprocess_test function

### ISSUE THREAD

**Issue by aelnouby** [longcw/yolo2-pytorch#51]
When trying the demo, I found that `preprocess_test` has two arguments `(data, size_index)` while in the demo.py file,  only one argument is passed `yolo_utils.preprocess_test((image, None, cfg.inp_size))[0]` , how to fix this ?

Thanks.

**Comment by lucheng07082221** [comment]
I got the same problem

**Comment by CompilerBian** [comment]
Try
```
im_data = np.expand_dims(
        yolo_utils.preprocess_test((image, None, cfg.inp_size), 0)[0], 0)
```
Then comment this line in preprocess_test
```
#inp_size = inp_size[size_index]
```

**Comment by lucheng07082221** [comment]
@CompilerBian thank you very much ,this problem had solved

**Comment by nijkah** [comment]
@CompilerBian I did it.(editing demo.py and utils/yolo.py) But I get this error.

TypeError: 'numpy.int64' object is not iterable

Same error occurs when removing comment sign in preprocess_test

**Comment by longcw** [comment]
Sorry for introduced this bug in the last PR. 
I just fixed this in the master branch: https://github.com/longcw/yolo2-pytorch/commit/dfdd82270cc946a8e9dcb5f99b5c9958bf05b0bd
