### ISSUE TITLE
demo.py makes TypeError: preprocess_test() missing 1 required positional argument: 'size_index'

### ISSUE THREAD

**Issue by NaJaeMin7** [longcw/yolo2-pytorch#56]
when I run demo.py, 
TypeError: preprocess_test() missing 1 required positional argument: 'size_index'
I saw #51 , I changed original code to

`im_data = np.expand_dims(
        yolo_utils.preprocess_test((image, None, cfg.inp_size), 0)[0], 0)`

but another error occurs.

`TypeError: 'numpy.int64' object is not iterable`

How can i fix this? thanks in advance.

**Comment by longcw** [comment]
Sorry for introduced this bug in the last PR.
I just fixed this in the master branch: dfdd822
