### ISSUE TITLE
yolo_to_bbox，bbox_ious, anchor_intersections

### ISSUE THREAD

**Issue by 22wei22** [longcw/yolo2-pytorch#60]
how can get the code of yolo_to_bbox，bbox_ious, anchor_intersections

**Comment by longcw** [comment]
These are written in Cython. You can find them in `.pyx` files:
https://github.com/longcw/yolo2-pytorch/blob/master/utils/bbox.pyx#L163
https://github.com/longcw/yolo2-pytorch/blob/master/utils/yolo.pyx
