### ISSUE TITLE
No module named _reorg_layer

### ISSUE THREAD

**Issue by skrish13** [longcw/yolo2-pytorch#8]
`yolo2-pytorch/layers/reorg/_ext/reorg_layer/__init__.py", line 3, in <module>`
 `from ._reorg_layer import lib as _lib, ffi as _ffi`
`ImportError: No module named _reorg_layer`

**Comment by longcw** [comment]
Did you try `./make.sh`

**Comment by skrish13** [comment]
No, I did not. Forgot to look in the documentation :disappointed: It works now. Thanks!
