### ISSUE TITLE
cython_bbox.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by yyhlvdl** [longcw/yolo2-pytorch#84]
from utils.cython_bbox import bbox_ious, anchor_intersections
ImportError: /home/xx/yolo2-pytorch/utils/cython_bbox.so: undefined symbol: _Py_ZeroStruct

**Comment by jundeli** [comment]
hi, how did you solve this error? now i am encountering the same error when running faster r-cnn.
